### ISSUE TITLE
Need 1 more filter

### ISSUE THREAD

**Issue by thie01tr** [thie01tr/capstone-project#12]
I have 2 filters working though there are some problems due to data from the api.

1. I had to run the api call in a for loop and passing it pages to get more of a variety of movies. Page 1 that we were receiving back only gets movies which vary in rating by maybe 0.2 and all have adult = false. This for loop is only grabbing 3 pages (1,201, 401) to try and get more variety but this is painstakingly slow. I could not find a call that will give any larger list/more varied
2. filtering on adult = true will give no movies, we need to find a way to get some movies in the list that have adult = true.  or filter on something else
3. Need to add 1 more filter
4. Need to work on looks
5. need to clean code

**Comment by pittmand** [comment]
The first page of results has ["adult": false,]. It's likely not a problem with the filter logic just none of the json result shave True for adult.
